version: '3.9'

services:
  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth-backend-test
    ports:
      - 27017:27017
  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379
